name: blogAPI CI/CD

on:
  push:
    branches:
      - "main"
      - "master"

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Push repo
        uses: actions/checkout@v4 #desde github/actions
      #- name: print hello
      #  run: echo "Hello world"
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - name: Upgrade Pip
        run: python -m pip install --upgrade pip
      - name: Install all dependencies
        run: pip install -r requirements.txt 
  
  
  Render-deployment:
    runs-on: ubuntu-latest
    needs: [build]

    environment: Render_production

    steps:
      - uses: actions/checkout@v4
      - uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{secrets.RENDER_SERVICE_ID}}
          api-key: ${{secrets.RENDER_API_KEY}}

  #Back4app-deployment:
  #  runs-on: ubuntu-latest
  #  needs: [build]

  #  environment: Back4app_production

  #  steps:
  #    - name: Get actions
  #      uses: actions/checkout@v4
  #    - name: Deploying to Back4app
  #      uses: back4app/Github-Ci-Cd-Example@v1 #The action
  #      with:
  #        project: ${{secrets.NAME_PROJECT}}
  #        accountKey: ${{secrets.ACCOUNT_KEY}}

      