name: blogAPI CI/CD

on:
  push:
    branches:
      - "main"
      - "master"

jobs: 
  build:
    runs-on: ubuntu-latest
      steps:
        - name: Push repo
          uses: actions/checkout@v4 #desde github/actions
        - name: print hello
          run: echo "Hello world"
